services:
  web:
    build: .  # 先构建镜像
    image: my-app:dev  # 构建后标记为该镜像名
    ports:
      - "80:80"
    env_file:
      - .env  # 开发环境配置
      - .env.secrets       # 密钥配置
    environment:
      - DB_HOST=db       # 新增变量
      - DB_PASSWORD=overwrite  # 覆盖env_file中的值