services:
  web:
    build: .  # 先构建镜像
    image: my-app:dev  # 构建后标记为该镜像名
    ports:
      - "80:80"
    environment:
      - RUN_MODE=dev-environment
    command: ["tini", "--", "/bin/sh", "-c", "sh ./test.sh; nginx -g 'daemon off;'"]